user root;
worker_processes 1;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    error_log /dev/null;

    server {
        listen 8080 default_server;
        server_name _;

        # مسیر دریافت ساب
        location /sub {
            alias /var/www/html/sub;
            default_type text/plain;
            add_header Cache-Control "no-cache";
        }

        # مسیرهای پروکسی (هدایت ترافیک به Xray)
        location /vless { proxy_pass http://127.0.0.1:10000; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }
        location /vmess { proxy_pass http://127.0.0.1:10001; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }
        location /ss { proxy_pass http://127.0.0.1:10002; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }
        location /trojan { proxy_pass http://127.0.0.1:10003; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }
        
        # تغییر حیاتی: برگرداندن 200 OK برای پاس کردن Health Check ریلی‌وی
        location / { 
            return 200 'Server is running.';
            add_header Content-Type text/plain;
        }
    }
}